---
- include: dependencies.yml
  when: ansible_os_family == 'Debian'
  tags:
  - apt

- include: sources_list.yml
  when: ansible_os_family == 'Debian'
  tags:
    - apt

- include: update.yml
  when: ansible_os_family == 'Debian'
  tags:
  - apt

- include: upgrade.yml
  when: ansible_os_family == 'Debian'
  tags:
  - apt

- include: packages.yml
  when: ansible_os_family == 'Debian'
  tags:
  - apt
