---
atom_ver: '1.11.2'
packer_version: '0.11.0'
terraform_version: '0.7.10'

docker_state: latest
docker_compose_state: latest
docker_machine_version: 0.8.2
docker_allowed_user:
  - charles

apt_sources_lists_extra:
    -
        comment: Google chrome repository
        file: /etc/apt/sources.list.d/google-chrome.list
        distrib: ubuntu
        repositories:
            -
                comment:
                enabled: true
                src_enabled: false
                url: 'https://dl.google.com/linux/chrome/deb/'
                section:  'stable'
                packages: ['main']
                section_prefix:
                section_suffix:
                archs: ['amd64']
                # key_server:
                key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
                # key_id:

apt_upgrade_type: dist
apt_upgrade: true

# list of extra packages to install
apt_extra_packages:
  - p7zip-rar
  - lftp
  - dos2unix
  - openssh-blacklist
  - openssh-blacklist-extra
  - openssl-blacklist
  - openssl-blacklist-extra
  - clamav
  - clamav-freshclam
  - vim-doc
  - trash-cli
  - mc
  - manpages-fr
  - manpages-fr-dev
  - manpages-fr-extra
  - git-extras
  - git-doc
  - synaptic
  - google-chrome-stable
  - ctags
  - vim-gnome
  - zsh
  - zsh-doc
  - terminator
  - gparted
  - fonts-inconsolata
  - cups-pdf
  - samba
  - bison
  - unace
  - filezilla
  - subversion
  - subversion-tools
  - git-flow
  - git-cola
  - git-svn
  - git-email
  - git-gui
  - mercurial
  - mercurial-git
  - hgsvn
  - cvs
  - cvs2svn
  - meld
  - firefox
  - firefox-locale-fr
  - thunderbird
  - thunderbird-locale-fr
  - thunderbird-gnome-support
  - chromium-browser
  - chromium-browser-l10n
  - chromium-codecs-ffmpeg
  - ubuntu-restricted-extras
  - keepassx
  - keepass2
  - keepass2-doc
  - libreoffice
  - graphviz
  - gimp
  - inkscape
  - caffeine
  - nautilus-dropbox
  - gnome-control-center
  - unity-chromium-extension
  - unity-tweak-tool
  - gedit-plugins
  - gedit-developer-plugins
  - ooo-thumbnailer
  - pidgin
  - vlc
  - openjdk-8-jre
  - openjdk-8-jdk
  - icedtea-8-plugin
  - gnucash
  - gwakeonlan

# list of packages to remove
apt_remove_packages: []

dnsmasq_addresses:
  -
    domain: localhost
    ip: 127.0.0.1
  -
    domain: dev
    ip: 127.0.0.1
  -
    domain: dev.localhost
    ip: 127.0.0.1
  -
    domain: dev.local
    ip: 127.0.0.1
  -
    domain: local.com
    ip: 127.0.0.1
  -
    domain: localhost.com
    ip: 127.0.0.1
