---
account_default_user: jc.bergot
account_default_user_fullname: JC BERGOT
account_default_user_email: 18658617+Brettdah@users.noreply.github.com

locale_generate:
  -
    lang: 'en_US'
    charset: 'UTF-8'
  -
    lang: 'fr_FR'
    charset: 'UTF-8'

locale_timezone_continent: Europe
locale_timezone_city: Paris

locale_default_lang: fr_FR
locale_default_charset: UTF-8

locale_env:
  lang: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  language: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_all: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_address: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_collate: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_ctype: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_identification: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_measurement: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_messages: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_monetary: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_name: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_numeric: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_paper: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_telephone: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  lc_time: "{{ locale_default_lang }}.{{ locale_default_charset }}"
  locpath: ~

keyboard_layout_reconfigure: true
keyboard_layout_code: fr

apt_sources_lists_default:
    # Debian
    -
        comment: Official repositories
        file: /etc/apt/sources.list
        distrib: Debian
        repositories:
            -
                comment: 'Main repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Updates repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}-updates"
            -
                comment: 'Security Updates repositories'
                enabled: true
                src_enabled: true
                url: 'http://security.debian.org/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}/updates"
            -
                comment: 'Backports repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}-backports"

    # Ubuntu
    -
        comment: Official repositories
        file: /etc/apt/sources.list
        distrib: Ubuntu
        repositories:
            -
                comment: 'Main repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu/'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Update repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu/'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-updates"
            -
                comment: 'Security Update repositories'
                enabled: true
                src_enabled: true
                url: 'http://security.ubuntu.com/ubuntu'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-security"
            -
                comment: 'Partner repositories'
                enabled: true
                src_enabled: true
                url: 'http://archive.canonical.com/ubuntu'
                packages: ['partner']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Backports repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-backports"

#apt_sources_lists_extra:
#    -
#        comment: Google chrome repository
#        file: /etc/apt/sources.list.d/google-chrome.list
#        distrib: ubuntu
#        repositories:
#            -
#                comment:
#                enabled: true
#                src_enabled: false
#                url: 'https://dl.google.com/linux/chrome/deb/'
#                section:  'stable'
#                packages: ['main']
#                archs: ['amd64']
#                # key_server:
#                key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
#                # key_id:
#    -
#        comment: Virtualbox repository
#        file: /etc/apt/sources.list.d/virtualbox.list
#        distrib: ubuntu
#        repositories:
#            -
#                comment:
#                enabled: true
#                src_enabled: false
#                url: 'http://download.virtualbox.org/virtualbox/debian'
#                packages: ['contrib']
#                archs: ['amd64']
#                # key_server:
#                key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#                # key_id:
apt_upgrade_type: dist
apt_upgrade: true

# list of extra packages to install
apt_extra_packages:
  - ack-grep # not in Ubuntu 17.10
  - dos2unix
  - fonts-inconsolata
  - git-doc
  - git-extras
  - git-flow
  - jq
  - manpages-fr
  - manpages-fr-dev
  - manpages-fr-extra
  - openssh-blacklist
  - openssh-blacklist-extra
  - openssl-blacklist
  - openssl-blacklist-extra
  - samba
  - sipcalc
  - trash-cli
  - unace
  - vim-doc

yum_repo_lists_default:
    #CentOS
    -
        distrib: "CenOS"
        repositories:
        - 
            name: "BaseOS"
            file: "CentOS-Base.repo"
            desc: "CentOS-$releasever - Base"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "yes"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra"
        -
            name: "AppStream"
            file: "CentOS-AppStream.repo"
            desc: "CentOS-$releasever - AppStream"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "yes"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra"
        -
            name: "centosplus"
            file: "CentOS-centosplus.repo"
            desc: "CentOS-$releasever - plus"
            checkgpg: "yeHighAvailabilitys"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra"
        -
            name: "cr"
            file: "CentOS-CR.repo"
            desc: "CentOS-$releasever - cr"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=cr&infra=$infra"
        -
            name: "base-debuginfo"
            file: "CentOS-Debuginfo.repo"
            desc: "CentOS-$releasever - Debuginfo"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl: 
              - "http://debuginfo.centos.org/$releasever/$basearch/"
        -
            name: "extras"
            file: "CentOS-Extras.repo"
            desc: "CentOS-$releasever - Extras"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "yes"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra"
        -
            name: "fasttrack"
            file: "CentOS-fasttrack.repo"
            desc: "CentOS-$releasever - fasttrack"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=fasttrack&infra=$infra"
        -
            name: "HighAvailability"
            file: "CentOS-HA.repo"
            desc: "CentOS-$releasever - HA"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=HighAvailability&infra=$infra"
        -
            name: "c8-media-BaseOS"
            file: "CentOS-Media.repo"
            desc: "CentOS-$releasever - Media"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl:
              - "file:///media/CentOS/BaseOS"
              - "file:///media/cdrom/BaseOS"
              - "file:///media/cdrecorder/BaseOS"
        -
            name: "c8-media-AppStream"
            file: "CentOS-Media.repo"
            desc: "CentOS-$releasever - Media"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "yes"
            baseurl:
              - "file:///media/CentOS/AppStream"
              - "file:///media/cdrom/AppStream"
              - "file:///media/cdrecorder/AppStream"
        -
            name: "PowerTools"
            file: "CentOS-PowerTools.repo"
            desc: "CentOS-$releasever - PowerTools"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra"
        -
            name: "BaseOS-source"
            file: "CentOS-Sources.repo"
            desc: "CentOS-$releasever - BaseOS Sources"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl:
              - "http://vault.centos.org/$contentdir/$releasever/BaseOS/Source/"
        -
            name: "AppStream-source"
            file: "CentOS-Sources.repo"
            desc: "CentOS-$releasever - AppStream Sources"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl:
              - "http://vault.centos.org/$contentdir/$releasever/AppStream/Source/"
        -
            name: "extras-source"
            file: "CentOS-Sources.repo"
            desc: "CentOS-$releasever - Extras Sources"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl:
              - "http://vault.centos.org/$contentdir/$releasever/extras/Source/"
        -
            name: "centosplus-source"
            file: "CentOS-Sources.repo"
            desc: "CentOS-$releasever - Plus Sources"
            checkgpg: "yes"
            gpgkeypath: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            enabled: "no"
            baseurl:
              - "http://vault.centos.org/$contentdir/$releasever/centosplus/Source/"

yum_extra_packages:
  - dos2unix
  - jq
  #- ack-grep # not in centos (may be EPEL)
  #- fonts-inconsolata
  #- git-doc
  #- git-extras
  #- git-flow
  #- manpages-fr
  #- manpages-fr-dev
  #- manpages-fr-extra
  #- openssh-blacklist
  #- openssh-blacklist-extra
  #- openssl-blacklist
  #- openssl-blacklist-extra
  #- samba
  #- sipcalc
  #- trash-cli # see in pip packages
  #- unace
  #- vim-doc



python_pip2_packages:
  - { name: 'jinja2-cli[yaml]'}

samba_workgroup: WORKGROUP

samba_users: {}
  # <user>: <password>
samba_shares: []
  # -
  #   path:
  #   group: ~
  #   public: no
  #   valid_users: []
  #   write_list: []
  #   create_mode: '0664'
  #   force_create_mode: '0664'
  #   directory_mode: '0775'
  #   force_directory_mode: '0775'

# list of packages to remove
apt_remove_packages: []

#dnsmasq_addresses:
#  -
#    domain: localhost
#    ip: 127.0.0.1
#  -
#    domain: dev
#    ip: 127.0.0.1
#  -
#    domain: dev.localhost
#    ip: 127.0.0.1
#  -
#    domain: dev.local
#    ip: 127.0.0.1
#  -
#    domain: local.com
#    ip: 127.0.0.1
#  -
#    domain: localhost.com
#    ip: 127.0.0.1

#docker_compose_by_pip: false
#docker_allowed_user:
#  - "{{ account_default_user }}"
#
#docker_debian_dependencies:
#  - apt-transport-https
#  - ca-certificates
#  - curl
#  - software-properties-common
#  - acl
#  - cgroup-lite
#  - apparmor
#  - linux-image-extra-virtual
#
#atom_users:
#  -
#    user: "{{ account_default_user }}"
#    packages:
#      - sync-settings
#
zsh_users:
  -
    user: "{{ account_default_user }}"
    env_vars:
      PATH: '$HOME/bin:/usr/local/bin:$PATH'
    theme: csa
    # custom theme files to copy to ~/.oh-my-zsh/themes
    custom_themes:
      - "{{ inventory_dir}}/files/home/oh-my-zsh/themes/csa.zsh-theme"
    plugins:
      - git
      - gitfast
      - python
      - debian
      - screen
      - git-extras
      - encode64

#aws_cli_users:
#  - "{{ account_default_user }}"

#aws_cli_bash_autocompletion: true
#aws_cli_zsh_autocompletion: true


account_users:
  "{{ account_default_user }}":
    name: "{{ account_default_user }}"
    comment: "{{ account_default_user_fullname }}"
    # home: # default = /home/<username>
    # home_mode: #default = 'u=rwx,g=rx,o=rx'
    # home_owner: # default = <username>
    # home_group: # default = <username>
    # no_chown_home: false
    # system: no # is system user ?
    # group: # primary group
    group: "{{ account_default_user }}"
    groups:
      - "{% if ansible_os_family|lower == 'debian' %}sudo{% elif ansible_os_family|lower == 'redhat' %}wheel{% endif %}"
    # append_groups: # default yes
    shell: /usr/bin/zsh
    # uid:
    # lock: false # lock password authentication : only ssh key authentication is allowed
    # salt: # password salt, default = None
    config_files:
      # -
      #   src: "home/{{ ansible_os_family|lower }}/.bashrc.j2"
      #   dest: # default in /home/<username>/
      #   owner: # default = <username>
      #   group: # default = <username>
      #   mode: # default = 'u=rw,g=r,o=r'
      #   backup: yes
      #   force: no
      -
        src: "home/{{ ansible_os_family|lower }}/.bashrc.j2"
        backup: yes
        force: no
      -
        src: home/.bash_aliases.j2
        backup: yes
        force: no
      -
        src: "{{ inventory_dir}}/files/home/.gitconfig"
      -
        src: "{{ inventory_dir}}/files/home/.gitignore"
    color_prompt: yes
    ssh_agent_autostart: no
    gitconfig:
      -
        name: 'user.name'
        option: '{{ account_default_user_fullname }}'
      -
        name: 'user.email'
        option: '{{ account_default_user_email }}'
  #  bash_aliases:
  #     <alias>: <command>
